language: node_js
node_js:
- '8'
install: yarn
script: yarn gulp
sudo: false
cache:
  yarn: true
  directories:
    - node_modules

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: d3fd51b5f31992c940800803aa545068a46af337
  keep-history: true
  verbose: true
  on:
    branch: master
